version: '3'
services:
  db:
    image:  mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    command: mysqld --innodb_use_native_aio=0
    volumes:
      - db_data:/var/lib/mysql
      - /etc/my.cnf:/etc/my.cnf 

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_SOURCE=user:password@tcp(db:3306)/dbname?charset=utf8&parseTime=True&loc=Local
    volumes:
      - .:/app

volumes:
  db_data: