@startuml

!define ENTITY_OMIT_FIELDS
!define ENTITY_ATTRIBUTES_ARE_PRIVATE
!define ENTITY_MEMBERS_ARE_PRIVATE

entity users as "users\nユーザー" {
  + id [PK]
  --
  # faculty_id [FK(users, id)] - 所属学部・院ID
  email: string

  uid:string - firebaseユーザー識別子
  created_at: datetime
  updated_at: datetime
  birth_date:datetime - 生年月日
  first_name:string - 名
  last_name:string - 姓
  first_name_kana:string - カナ名
  last_name_kana:string - カナ姓
  birth_date:datetime - 生年月日
  content_type: integer
}

entity faculties as "researchers\n所属学部・院テーブル" {
  + id [PK]
  --
  name:string - 名前
  order:integer - 順序
  created_at: datetime
  updated_at: datetime
}

entity researchers as "researchers\n研究者" {
  + id [PK]
  --
  # user_id [FK(users, id)] - ユーザーID
  created_at: datetime
  updated_at: datetime
}

entity students as "students\n学生" {
  + id [PK]
  --
  # user_id [FK(users, id)] - ユーザーID
  age: integer - 年齢
  sex: integer  - 性別
  grade: integer - 学年
  created_at: datetime
  updated_at: datetime
}

entity likes as "likes\nいいね" {
  + id [PK]
  created_at: datetime
  updated_at: datetime
  --
  user_id [FK(users, id)]
  post_id [FK(posts, id)]
}

entity recruit as "posts\n投稿" {
  + id [PK]
  --
  # researcher_id [FK(researcher_id, id)] - 研究者ID
  # message_room_id [FK(messeage_rooms, id)] - メッセージルームID
  title: string
  description: text
  caution: string
  restriction: string
  project: integer
  rabo: string
  testing_field: string
  experment_period: string
  meet_time: string
  reward: string
  item: string
  count: integer
  is_active: boolean
  recruitment_period: date
  created_at: datetime
  updated_at: datetime
  --
  user_id [FK(users, id)]
}

entity recruit_student as "被験者応募者テーブル"  {
  + id [PK]
  --
  # recruit_id [FK(post_id, id)] - 投稿ID
  # student_id [FK(student_id, id)] - 学生ID
  created_at: datetime
  updated_at: datetime
}


entity messeage_rooms as "messeage_rooms\nメッセージルーム" {
  + id [PK]
  --
  # student_id [FK(student_id, id)] - 学生ID
  # researcher_id [FK(researcher_id, id)] - 研究者ID
  title:string - 名前
  created_at:datetime - 作成日
  updated_at:datetime - 更新日
}


entity messages as "messages\nメッセージ" {
  + id [PK]
  --
  # message_room_id [FK(room_id, id)] - ルームID
  content:string - 本文
  sender: integer - 送信者
  created_at:datetime - 作成日
  updated_at:datetime - 更新日
}

entity appointments as "appointments\n被験者申し込み" {
  + id [PK]
  --
  # post_id [FK(post_id, id)] - 学生ID
  # student_id [FK(student_id, id)] - 学生ID
  # researcher_id [FK(researcher_id, id)] -研究者ID
  status:integer - enum("申込中", "受け入れ", "拒否")
  responded_at:datetime - 返答日時
  created_at:datetime - 作成日
  updated_at:datetime - 更新日
}

users }o--|| faculties
users }o--o{ students
users }o--o{ researchers
students ||--o{ messeage_rooms
researchers ||--o{ messeage_rooms
messeage_rooms ||--o{ messages
posts ||--o{ likes
students ||--o{ appointments
researchers ||--o{ appointments
researchers ||--o{ posts
