name: Go ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dbname
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Lint
        run: |
          $(go env GOPATH)/bin/goimports -w .
          gofmt -s -w .
        working-directory: app

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Wait for MySQL
        timeout-minutes: 2
        run: |
          until nc -zv localhost 3306; do
            echo "Waiting for MySQL service..."
            sleep 5
          done

      - name: Tidy dependencies
        run: go mod tidy
        working-directory: app

      - name: Download dependencies
        run: go mod download
        working-directory: app

      - name: Build
        run: go build -v .
        working-directory: app

      - name: Test
        run: go test -v .
        working-directory: app